//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webprojesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciRolleri
    {
        public int ID { get; set; }
        public int KullaniciID { get; set; }
        public int RolID { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Roller Roller { get; set; }
    }
}
