//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webprojesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanicilar()
        {
            this.KullaniciRolleris = new HashSet<KullaniciRolleri>();
            this.Sepets = new HashSet<Sepet>();
            this.Satislars = new HashSet<Satislar>();
        }

        public int Id { get; set; }
        [Display(Name = "Kullanici Adi")]
        [Required(ErrorMessage = "Kullanici Adi bos gecilmez!")]
        public string KullaniciAdi { get; set; }
        [Required(ErrorMessage = "Sifre bos gecilmez!")]
        public string Sifre { get; set; }

        [Display(Name = "Adi Soyadi")]
        [Required(ErrorMessage = "Adi Soyadi bos gecilmez!")]
        public string AdiSoyadi { get; set; }
        [Required(ErrorMessage = "Telefon bos gecilmez!")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
                   ErrorMessage = "Uygun formatta telefon numarası giriniz.")]
        public string Telefon { get; set; }
        [Required(ErrorMessage = "Adres bos gecilmez!")]
        public string Adres { get; set; }
        [Display(Name = "E-mail")]
        [Required(ErrorMessage = "E-mail bos gecilmez!")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$",
            ErrorMessage = "Lütfen uygun formatta e-mail adresi giriniz.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Tarih bos gecilmez!")]
        public System.DateTime Tarih { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciRolleri> KullaniciRolleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet> Sepets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar> Satislars { get; set; }
    }
}
